<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
    <title>Title</title>
</head>
<body>
<h2>Shampoo detail</h2>
<?php
echo '<h3>' . $shampoo['brand'] . '</h3>';
echo '<p>' . $shampoo['variant'] . '</p>';
echo '<p>' . $shampoo['hair_type'] . '</p>';
echo '<p>' . $shampoo['size'] . '</p>';
echo '<p>' . $shampoo['scent'] . '</p>';
echo '<p>' . $shampoo['ingredient'] . '</p>';
echo '<p>£' . $shampoo['price'] . '</p>';
?>
</body>
</html>